spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: school
    password: BX5201314
    url: jdbc:mysql://47.92.98.224:3306/school
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
#  redis:
#    host: 39.108.209.221
#    port: 6379
#    password:

http:
  multipart:
    max-request-size: 100MB
    max-file-size: 100MB
    resolve-lazily: true
